import express from "express";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";
import nodemailer from "nodemailer";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // --- API Routes ---

  // 1. Get Google OAuth URL
  app.get('/api/auth/google/url', (req, res) => {
    const clientId = process.env.GOOGLE_CLIENT_ID;
    const redirectUri = `${process.env.APP_URL}/auth/callback`;

    if (!clientId) {
      return res.status(500).json({ error: 'Google Client ID not configured' });
    }

    const params = new URLSearchParams({
      client_id: clientId,
      redirect_uri: redirectUri,
      response_type: 'code',
      scope: 'email profile openid',
      access_type: 'offline',
      prompt: 'consent'
    });

    const authUrl = `https://accounts.google.com/o/oauth2/v2/auth?${params.toString()}`;
    res.json({ url: authUrl });
  });

  // 2. Checkout & Email Notification
  app.post('/api/checkout', async (req, res) => {
    const { formData, cartTotal, shippingCost, finalTotal } = req.body;

    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_APP_PASSWORD
      }
    });

    const emailHtml = `
      <div style="font-family: 'serif', 'Georgia', serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 20px;">
        <h1 style="color: #000; border-bottom: 2px solid #FFDBE9; padding-bottom: 10px;">New Order - Hamzil.</h1>
        
        <div style="margin: 20px 0;">
          <h2 style="font-size: 18px; color: #333;">Customer Details:</h2>
          <p><strong>Name:</strong> ${formData.firstName} ${formData.lastName}</p>
          <p><strong>Email:</strong> ${formData.email}</p>
          <p><strong>Phone:</strong> ${formData.phone}</p>
        </div>

        <div style="margin: 20px 0; background: #fafafa; padding: 15px; border-radius: 10px;">
          <h2 style="font-size: 18px; color: #333;">Shipping Address:</h2>
          <p>${formData.address}</p>
          <p>${formData.apartment || ''}</p>
          <p>${formData.city}, ${formData.postalCode}</p>
          <p>${formData.country}</p>
        </div>

        <div style="margin: 20px 0;">
          <h2 style="font-size: 18px; color: #333;">Financial Summary:</h2>
          <p>Subtotal: Rs. ${cartTotal.toFixed(2)}</p>
          <p>Shipping: ${shippingCost === 0 ? 'FREE' : `Rs. ${shippingCost.toFixed(2)}`}</p>
          <hr />
          <p style="font-size: 20px; font-bold;"><strong>Total: Rs. ${finalTotal.toFixed(2)}</strong></p>
          <p style="color: #FF7EB3;">Method: Cash on Delivery (COD)</p>
        </div>

        <p style="font-size: 12px; color: #888; margin-top: 30px; text-align: center;">
          This order was generated by the Hamzil Specialist Collection storefront.
        </p>
      </div>
    `;

    try {
      await transporter.sendMail({
        from: `"Hamzil Store" <${process.env.EMAIL_USER}>`,
        to: process.env.EMAIL_USER, // Send to yourself
        subject: `🚨 NEW ORDER from ${formData.firstName} - Rs. ${finalTotal.toFixed(0)}`,
        html: emailHtml
      });

      res.status(200).json({ success: true });
    } catch (error) {
      console.error('Email error:', error);
      res.status(500).json({ error: 'Failed to send confirmation email' });
    }
  });

  // 3. OAuth Callback Handler
  app.get('/auth/callback', (req, res) => {
    // In a real app, you would exchange the code for tokens here
    // and create a session. For this demo, we'll simulate success.
    const { code } = req.query;

    if (code) {
      res.send(`
        <html>
          <body>
            <script>
              if (window.opener) {
                window.opener.postMessage({ type: 'OAUTH_AUTH_SUCCESS', code: '${code}' }, '*');
                window.close();
              } else {
                window.location.href = '/';
              }
            </script>
            <p>Authentication successful. You can close this window.</p>
          </body>
        </html>
      `);
    } else {
      res.status(400).send('Authentication failed');
    }
  });

  // --- Vite Middleware ---
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    // Serve static files in production (if built)
    app.use(express.static('dist'));
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
